### ISSUE TITLE
Screen reader support

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-avatar#10]
for vaadin-avatar and vaadin-avatar-group

**Comment by knoobie** [comment]
@web-padawan I'm wondering, why is `vaadin-avatar` an image (`role="image"`)? In my understanding it's more like a button / a group of buttons, especially if you are going to add a clicklistener or space-listener to it for interaction. (For example, to show more informations about the selected user in a dialog)

Additionally, I would propose to add `aria-hidden="true"` to the `svg`s and `img` inside `<vaadin-avatar>` because not every screenreader is capable of handling shadow-dom properly. 

Another improvement could be, to add the `abbr` if present inside title of `<vaadin-avatar>`.

Examples:
 - name = Max Mustermann, abr = null -> title = Max Mustermann 
 - name = Max Mustermann, abr = MM -> title = Max Mustermann (MM)
 - name = null abr = MM -> title = MM
 - name = null abr = null -> title = anonymous (<- this should be customizable (i18n))

`<vaadin-avatar-group>`should get an additional `aria-label` with an i18n-able string like "Currently active users:" or "current online users:".

**Comment by web-padawan** [comment]
@knoobie thanks for your feedback. I was wondering whether `role="image"` is the right one, and wasn't sure.

Your ideas make a lot of sense. I will submit a PR to address those on Monday and will let you know.

**Comment by knoobie** [comment]
I was thinking about adding `aria-live` to `<vaadin-avatar-group>` as well. Sadly because of some restrictions aria-live has at the moment, the only way to really notify the Screenreader about changes inside the group would be an element that is always present on first rendering (see  https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions ) I'm not an expert when it comes to `aria-live`, so I'm not sure if it's enough to be added to the group or it has to be done on the initial page load, like done pre Vaadin 10 with the "announcer region" on the bottom. 

Totally out of scope: That reminds me.. it woul be a really good addition to have some kind of `<vaadin-sr-announcer>` that is I always present on the page and listens to events / can be interacted with from the server side.

**Comment by web-padawan** [comment]
@knoobie we are using `iron-a11y-announcer` in some components (e.g. to announce focused date change in date-picker). I will create an issue to investigate.

**Comment by web-padawan** [comment]
@knoobie based on your feedback, I reported the issues: #43, #44, #45, #46, #47

Most of these issues aren't big, so I'm going to handle them in the same PR. The only issue that needs clarification would be using `aria-live` for the group, so I tagged you in the issue (#44) as well. Let's continue discussion there.
