### ISSUE TITLE
No fallback to abbr if image could not be loaded

### ISSUE THREAD

**Issue by bcersows** [vaadin/vaadin-avatar#111]
If the target URL of an avatar is not reachable, then instead of showing the browser img error icon it should fall back and display the abbreviation (if given).

Current:
![image](https://user-images.githubusercontent.com/1199637/112985367-60b08080-9160-11eb-8c15-98a68a964546.png)

Expected:
avatar as if no img was given (hide the img, show the `abbr` part)

Possible solution:
This could be done by adding an [`onerror` listener](https://www.w3schools.com/jsref/event_onerror.asp) to the `img` tag which handles updating the visibilities. Example: `onerror="this.style.display='none'"`

**Comment by Peppe** [comment]
Thanks for the feedback. Here's how I think it should behave.
When an image is being loaded and it can't be loaded due to some problem (404, etc.):
- Treat avatar like image is not set. Use the same order to decide if abbr or name should be used for the box.
- Do a console.warn() when this happen, so that the developer knows what is wrong. It can be confusing to set an image, but then everything works, but no image in sight. With an warning, you would know what is wrong.

**Comment by bcersows** [comment]
Thanks, y'all! :)
