### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-avatar#8]
For avatar and avatar-group
- Lumo
- Material
- should use user colors defined by the theme
- themable parts?
  - not for now unless we come up with something important

**Comment by jouni** [comment]
This depends a bit on how we want to allow customizing the default icon (#12). If we implement the icon with a pseudo element on the host, then we don’t need any parts.

It might be more future-proof to give the icon its own part, if we for example need to use the host pseudo elements for some other styling needs (interaction or other state indication).

**Comment by jouni** [comment]
Lumo theme should have predefined size variants, for both vaadin-avatar and vaadin-avatar-group.

- theme="xlarge" → --lumo-size-xl
- theme="large" → --lumo-size-l
- default → --lumo-size-m
- theme="small" → --lumo-size-s
- theme="xsmall" → --lumo-size-xs

When applied on the avatar-group, it should propagate the variant to all the avatar items. The sizing should affect the clipping mask as well, so that the overlap and the border/margin is always a full pixel value.

<img width="756" alt="avatar-size-variants" src="https://user-images.githubusercontent.com/66382/85520956-431c1c80-b60c-11ea-9f22-30ea046b6004.png">

The Material theme will only have one size, which is 2.25rem (36px).

**Comment by jouni** [comment]
Note, that the sizing of the icon and the abbreviation in those size variants is not specific. That needs to be adjusted in code, so that it looks good in all sizes. 

In the mockup, the smaller sizes have less padding around the icon and the abbreviation than in the bigger sizes. Not sure if that’s possible to achieve with computed sizing / automatic svg text scaling.
