### ISSUE TITLE
NaN in overflow avatar

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-avatar#83]
UPDATE: steps to reproduce in [this comment](https://github.com/vaadin/vaadin-avatar/issues/83#issuecomment-706054103).

---

Not sure what are the exact conditions for this bug to occur, but it can be seen at least in the [Collaboration Engine Demo](https://collaboration-engine.demo.vaadin.com/), when there are many users looking at the same form.

As you can see in the screenshot below, the avatar group has 9 items (see the inspector). The group displays all of these 9 avatars, and a redundant overflow avatar. The overflow dropdown contains a copy of all the 9 avatars.

After resizing the window, the group is updated to display only ~3 avatars and others hidden behind the overflow (which works fine in this case), although there should be enough space to display more avatars.

![image](https://user-images.githubusercontent.com/28533233/95553722-bc067f00-0a17-11eb-8943-5789e1f7396c.png)

**Comment by Peppe** [comment]
The view is coded to only show the three faces plus the overflow, so already having that many avatars visible is part of the bug.

https://github.com/vaadin/ce-demo/blob/master/src/main/java/com/jensjansson/ce/views/persons/PersonsView.java#L90-L92
```
avatarGroup = new CollaborationAvatarGroup(
            localUser);
avatarGroup.setMaxItemsVisible(4);
```

**Comment by pekam** [comment]
Oh, good point! So after resizing it works as expected.

**Comment by Peppe** [comment]
I found a way to rerproduce it. If you switch to a row that has zero avatars in the `vaadin-avatar-group`, and then switch to a item that would have the overflow avatar, then it will count it wrong somehow and produce a +NaN overflow with many avatars visible. the aria-label has however the correct count in  "Currently 9 active users". You have to be a bit quick when testing, because the bot joins into the empty collaboration item after a while, and then the bug doesn't happen anymore.

![ce-demo-nan](https://user-images.githubusercontent.com/525503/95559477-7ef2ba80-0a20-11eb-91c3-292ae40460e4.gif)

**Comment by pekam** [comment]
Steps to reproduce in the web component demo and Chrome dev tools:
1. Open [the wc demo](https://cdn.vaadin.com/vaadin-avatar/1.0.0/demo/#avatar-group-demos)
2. Open the inspector and select the second avatar group in the page (the one that has `maxItemsVisible`)
3. Toggle the items to an empty array and back in the inspector's console:
```js
const i = $0.items
$0.items = []
$0.items = i
```

![image](https://user-images.githubusercontent.com/28533233/95562987-85cffc00-0a25-11eb-8332-977a1ce1c608.png)
